### ISSUE TITLE
Crash using enumerate in Beamer since update to 77b5509 (probably relates to c7483c9, 9e9d241 or c9df8c3)

### ISSUE THREAD

**Issue by prowlett** [coursebuilder-ncl/makecourse#77]
I've updated `makecourse` from eb9acb4 to 77b5509 and re-ran. Some Beamer slides I wrote in October are now failing to render. I'm not totally sure why they are trying to re-render because they haven't been edited since I last build the course. The course built fine under eb9acb4, but I'm not sure if these slides re-rendered then or not, because I wouldn't expect them to try, having not been edited recently.

I tracked down the error to a `frame` where I use `enumerate`. `makecourse` stalls with "`UndefinedError: 'plasTeX.Base.LaTeX.Lists.enumerate_ object' has no attribute 'term'`".

Here is a simple example that has the problem. 

```
\documentclass{beamer} 
\begin{document}
    \begin{frame}
        \begin{enumerate}
            \item 1
            \item 2
            \item 3
        \end{enumerate}
    \end{frame}
\end{document}
```

The output of `makecourse -vv` up to the crash is like this:

```
makeCourse.render:render_item:55: INFO:	Rendering: test-folder/slides.tex
makeCourse.render:render_item:56: DEBUG:	Rendering slides "Test slides" using slides.html using relative paths.

DEBUG: PlasTeX: test-folder/slides.tex
 ( /home/.../coursebuilder_env/lib/python3.8/site-
   packages/makeCourse/plastex/beamer/__init__.py
 ( /home/.../coursebuilder_env/lib/python3.8/site-
   packages/makeCourse/plastex/graphicx/__init__.py
 ) )
INFO: Importing templates from
   /home/.../coursebuilder_env/lib/python3.8/site-
   packages/plasTeX/Renderers/PageTemplate
INFO: Importing templates from
   /home/.../coursebuilder_env/lib/python3.8/site-
   packages/makeCourse/plasTeXRenderer
INFO: Importing templates from
   /home/.../coursebuilder_env/lib/python3.8/site-
   packages/makeCourse/plasTeXRenderer/Themes/default
 [ test/test_slides/index.htmlUndefinedError: 'plasTeX.Base.LaTeX.Lists.enumerate_ object' has no attribute 'term'
```

I noticed that the same problem does not occur with the `article` class. Making a `chapter` rather than `slides` with this code builds fine:

```
\documentclass{article} 
\begin{document}
    \begin{enumerate}
       	\item 1
       	\item 2
       	\item 3
    \end{enumerate}
\end{document}
```

I also tried this, in case the problem related to enumerate being inside something else (a `frame`), but this worked fine.

```
\documentclass{article} 
\begin{document}
    \begin{minipage}[t]{10cm}
        \begin{enumerate}
            \item 1
            \item 2
            \item 3
        \end{enumerate}
    \end{minipage}
\end{document}
```

So I think the problem is somehow to do with `enumerate` interacting with `beamer`/`makecourse`'s `slides`. 

I notice some commits since I last updated (c7483c9, 9e9d241 or c9df8c3) refer to `enumerate` and `enumitem` and wonder if this is relevant.

**Comment by georgestagg** [comment]
Thanks, the latest commit should hopefully fix that. I've tweaked a lot with slides recently, best to keep an eye on them if you're tracking the master branch closely.

**Comment by prowlett** [comment]
Yes, that works now, thanks!
